FROM openjdk:17-jdk-slim

WORKDIR /app
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

ARG SPRING_ACTIVE_PROFILE
ARG SPRING_DATABASE_USERNAME
ARG SPRING_DATABASE_PASSWORD

ENV ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
ENV DATASOURCE_USERNAME=${SPRING_DATABASE_USERNAME}
ENV DATASOURCE_PASSWORD=${SPRING_DATABASE_PASSWORD}

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
