FROM openjdk:17-jdk-slim

WORKDIR /app
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

ARG SPRING_ACTIVE_PROFILE
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV SPRING_PROFILES_ACTIVE=${SPRING_ACTIVE_PROFILE}
ENV SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]