spring:
  application:
    name: junmo-website
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://junmo-website-db01.ct2aoqa2kuhu.ap-northeast-2.rds.amazonaws.com:3360/website?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      username: ${SPRING_DATABASE_USERNAME}
#      password: ${SPRING_DATABASE_PASSWORD}
  datasource:
    url: jdbc:mysql://junmo-website-db01.ct2aoqa2kuhu.ap-northeast-2.rds.amazonaws.com:3360/website?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
