name: Java CI with Gradle

# main이 push 할때만 깃허브액션동작
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    # Gradle Wrapper 스크립트 파일 (gradlew)에 실행 권한을 부여
    # gradlew wrappe 통해 빌드된거 밀고, jar 파일생성
    - name: Build Spring Project
      run: |
        chmod +x ./gradlew
        ./gradlew wrapper 
        ./gradlew clean bootjar

    # Build & Push Docker Image
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker Spring Project Image
      uses: docker/build-push-action@v5
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/junmo-website-backend:latest
        
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: EC2 Docker Compose Update and Run
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        port: 22
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          export SPRING_ACTIVE_PROFILE=${{ secrets.SPRING_ACTIVE_PROFILE }}
          export SPRING_DATABASE_USERNAME=${{ secrets.SPRING_DATABASE_USERNAME }}
          export SPRING_DATABASE_PASSWORD=${{ secrets.SPRING_DATABASE_PASSWORD }}
          echo "SPRING_ACTIVE_PROFILE: $SPRING_ACTIVE_PROFILE"
          echo "SPRING_DATABASE_USERNAME: $SPRING_DATABASE_USERNAME"
          echo "SPRING_DATABASE_PASSWORD: $SPRING_DATABASE_PASSWORD"
          cd /docker-compose
          sudo -E docker-compose pull
          sudo -E docker-compose up -d --force-recreate

